apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      serviceAccountName: msa-service-account
      containers:
      - name: frontend-service
        image: wo9697/frontend-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
