resources:
- namespace.yaml
- configmap-secret.yaml

- auth/deployment.yaml
- auth/mariadb.yaml

- board/deployment.yaml
- board/mariadb.yaml

- incident/deployment.yaml
- incident/mariadb.yaml

- gateway/deployment.yaml
- frontend/deployment.yaml
