resources:
- namespace.yaml
- configmap-secret.yaml

- auth/deployment.yaml
- auth/mariadb.yaml
- auth/hpa.yaml

- board/deployment.yaml
- board/mariadb.yaml
- board/hpa.yaml

- incident/deployment.yaml
- incident/mariadb.yaml
- incident/hpa.yaml

- gateway/deployment.yaml
- gateway/service.yaml

- frontend/deployment.yaml
- frontend/service.yaml

- ingress.yaml

- security/serviceaccount.yaml
- security/rbac.yaml
- security/networkpolicy-default-deny.yaml
- security/networkpolicy-allow-internal.yaml
- security/networkpolicy-allow-ingress.yaml
- security/networkpolicy-allow-monitoring.yaml
