apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-service
  namespace: incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      serviceAccountName: msa-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - board-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: board-service
        image: wo9697/board-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
