apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: msa-service-account
      containers:
      - name: api-gateway
        image: wo9697/api-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
